#! /usr/bin/env bash

# set -eo pipefail
# trap "exit" 2



source .env || "couldn't locate .env"

echo "=== Generating secrets..."

set -e

sodium_secret_key_env=".env.sodium_secret_key"
sodium_public_key_env=".env.sodium_public_key"
env=".env"



# image="placeos/init:${PLACE_INIT_TAG:-latest}"

# docker pull "${image}"

# docker run --rm -v "${PWD}:/tmp/secrets" -w /tmp/secrets -- "${image}" generate-secrets
