require "secrets-env"
require "sodium"

module App
  CLIENT_PORTAL_URI = ENV["CLIENT_PORTAL_URI"]? || "http://127.0.0.1:3000" # change to http://placeos.run when ready

  # generated by deployment tooling
  PLACEOS_INSTANCE_ID     = ENV["PLACEOS_INSTANCE_ID"]? || abort "No Instance ID set in environment" # change this
  PLACEOS_INSTANCE_SECRET = ENV["PLACEOS_INSTANCE_SECRET"]
  SECRET_KEY              = Sodium::Sign::SecretKey.new(App::PLACEOS_INSTANCE_SECRET.hexbytes)
  INSTANCE_DOMAIN         = ENV["INSTANCE_DOMAIN"]? || "http://localhost:3000"
end
