require "secrets-env"

module App
  CLIENT_PORTAL_URI   = ENV["CLIENT_PORTAL_URI"]? || "http://127.0.0.1:3000"
  
  # generated by deployment tooling
  PLACEOS_INSTANCE_ID = ENV["PLACEOS_INSTANCE_ID"]? || abort "No Instance ID set in environment" # change this
  PLACEOS_INSTANCE_SECRET = ENV["PLACEOS_INSTANCE_SECRET"]?

  # secret
  # private key
end
