name: CI

on:
  push:

jobs:
  style:
    uses: PlaceOS/.github/.github/workflows/crystal-style.yml@main

  test:
    runs-on: ubuntu-latest
    name: "${{ !matrix.stable && '🚧 ' || ''}}crystal: ${{ matrix.crystal }}"
    continue-on-error: ${{ !matrix.stable }}
    services:
      rethink:
        image: rethinkdb:2.4
        ports:
        - 29015:29015
        - 28015:28015
    strategy:
      fail-fast: false
      matrix:
        stable: [true]
        crystal:
          - 1.1.1
        include:
          - crystal: 1.2.1
            stable: false
          - crystal: nightly
            stable: false
    steps:
      - uses: crystal-lang/install-crystal@v1.5.1
        with:
          crystal: ${{ matrix.crystal }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec --error-trace --verbose --order random
