name: CI

on: [push]

jobs:
  style:
    runs-on: ubuntu-latest
    container: crystallang/crystal:latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: crystal tool format --check
      - name: Lint
        uses: crystal-ameba/github-action@v0.2.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    name: "crystal: ${{ matrix.crystal }}, stable: ${{ matrix.stable }}"
    continue-on-error: ${{ !matrix.stable }}
    services:
      rethink:
        image: rethinkdb:2.4
        ports:
        - 29015:29015
        - 28015:28015
    strategy:
      fail-fast: false
      matrix:
        stable: [true]
        crystal:
          - 1.1.1
        include:
          - crystal: nightly
            stable: false
    steps:
      - uses: crystal-lang/install-crystal@v1.5.1
        with:
          crystal: ${{ matrix.crystal }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec --error-trace -v
